name: 'stackit-cli tools installer'
description: |-
  Install a specific version of the stackit-cli binary. Acceptable values are latest
  or any semantic version string like 0.31.0.
  
  https://github.com/stackitcloud/stackit-cli
inputs:
  version:
    description: 'Version of stackit-cli'
    required: true
    default: 'latest'
outputs:
  path:
    description: 'Path to the cached stackit-cli binary'
branding:
  icon: 'terminal'
  color: 'gray-dark'
runs:
  using: node20
  main: 'dist/index.js'
